apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-volumeclaim
  namespace: dynamodb
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  namespace: dynamodb
  labels:
    app: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rigr720xd
      containers:
      - image: amazon/dynamodb-local
        name: dynamodb-local
        command: ['java']
        args: ['-Xms256m', '-Xmx2048m', '-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '/home/dynamodblocal/data']
        resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "4G"
              cpu: "4"
        ports:
        - containerPort: 8000
        volumeMounts:
            - mountPath: /home/dynamodblocal/data
              name: dynamodb
      volumes:
        - name: dynamodb
          persistentVolumeClaim:
            claimName: dynamodb-volumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  namespace: dynamodb
  labels:
    app: dynamodb
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: dynamodb