apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  annotations: 
       nginx.ingress.kubernetes.io/rewrite-target: / 
  name: grafana-ui 
  namespace: monitoring 
spec: 
  ingressClassName: public 
  rules: 
  - host: grafana-ui.local 
    http: 
      paths: 
      - backend: 
          service: 
            name: grafana 
            port: 
              number: 3000 
        path: / 
        pathType: Prefix 