apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  annotations: 
       nginx.ingress.kubernetes.io/rewrite-target: / 
  name: prometheus-ui 
  namespace: monitoring 
spec: 
  ingressClassName: public 
  rules: 
  - host: prometheus-ui.local 
    http: 
      paths: 
      - backend: 
          service: 
            name: prometheus-k8s 
            port: 
              number: 9090 
        path: / 
        pathType: Prefix 