apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql14-volumeclaim
  namespace: pgsql
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql14
  namespace: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql14
  template:
    metadata:
      labels:
        app: pgsql14
      namespace: pgsql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rigr720xd
      containers:
        - name: postgres
          image: arylwen/postgis:14-3.4-huge-pages 
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "20G"
              cpu: "5"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgresdb"
            - name: POSTGRES_USER
              value: "pguser"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-password
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pgsql14-volumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql14
  namespace: pgsql
  labels:
    app: pgsql14
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pgsql14