apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql14-volumeclaim
  namespace: pgsql
spec:
  storageClassName: mayastor-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql14
  namespace: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql14
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgsql14
      namespace: pgsql
    spec:
      containers:
        - name: postgres
          image: arylwen/postgis:14-3.3-huge-pages 
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgresdb"
            - name: POSTGRES_USER
              value: "pguser"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-password
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pgsql14-volumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql14
  namespace: pgsql
  labels:
    app: pgsql14
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pgsql14