apiVersion: v1 
kind: Pod 
metadata: 
  name: semsearch-ui 
spec: 
  containers: 
  - image: nginx:alpine 
    name: web-server 
    volumeMounts: 
    - name: html 
      mountPath: /usr/share/nginx/html 
      readOnly: true 
    ports: 
    - containerPort: 80 
      protocol: TCP 
  volumes: 
  - name: html 
    gitRepo: 
      repository: https://github.com/arylwen/mlk8s.git 
      revision: master 
      directory: apps/semsearch/search_ui/semsearch_ui_deployment