apiVersion: v1
kind: Service
metadata:
  labels:
    app: semsearch-clip-milvus-redis-pg 
    app.kubernetes.io/name: semsearch
  name: semsearch-clip-milvus-redis-pg
  namespace: semsearch
spec:
  ports:
    - port: 5000
      name: semsearch-api-port
      protocol: TCP
      targetPort: 5000
  selector:
    app: semsearch-clip-milvus-redis-pg
  type: NodePort
status:
  loadBalancer: {}
