apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  annotations: 
       nginx.ingress.kubernetes.io/rewrite-target: / 
  name: airflow-ui 
  namespace: airflow 
spec: 
  ingressClassName: public 
  rules: 
  - host: airflow-ui.local 
    http: 
      paths: 
      - backend: 
          service: 
            name: airflow-webserver 
            port: 
              number: 8080 
        path: / 
        pathType: Prefix 