#FROM rayproject/ray-ml:31ab8a-py310-gpu
FROM rayproject/ray:2.5.1.1d09d6-py310-cu117
#python 3.10.8

#COPY pip.conf /home/ray/.pip/pip.conf
RUN /home/ray/anaconda3/bin/pip install -U pip

RUN pip install protobuf==3.20.2        #3.19.6
RUN pip install python-dotenv==1.0.0
RUN pip install cachetools==5.3.0       #5.3.1
RUN pip install click==8.1.3
RUN pip install psutil==5.9.4           #5.9.5
RUN pip install requests==2.28.2        #2.31.0
RUN pip install six==1.16.0             #1.13.0
RUN pip install sseclient==0.0.27

RUN pip install pandas==1.5.3
RUN pip install numpy==1.22.4

#RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
#cuda 11.7 - cuda 11.8 is not compatible with anything
RUN pip install torch torchvision torchaudio 

RUN pip install "ray[all]"==2.5.0
RUN pip install deepspeed==0.8.3
RUN pip install pyarrow==12.0.1

RUN pip install transformers==4.29
RUN pip install huggingface_hub==0.13.2
RUN pip install accelerate==0.20.3
RUN pip install sentencepiece==0.1.97
RUN pip install tokenizers==0.13.3

RUN pip install aleph_alpha_client==2.16.1
RUN pip install anthropic==0.2.3
RUN pip install openai==0.27.2

USER root
CMD source /home/ray/.bashrc
