FROM rayproject/ray:2.5.1.1d09d6-py310-cpu

#COPY pip.conf /home/ray/.pip/pip.conf
RUN /home/ray/anaconda3/bin/pip install -U pip

RUN pip install aleph_alpha_client==2.16.1
RUN pip install anthropic==0.2.3
RUN pip install cachetools==5.3.0
RUN pip install click==8.1.3
#RUN pip install Flask==2.2.3
#RUN pip install Flask_Cors==3.0.10
RUN pip install huggingface_hub==0.13.2
RUN pip install openai==0.27.2
RUN pip install psutil==5.9.4
RUN pip install python-dotenv==1.0.0
RUN pip install requests==2.28.2
RUN pip install six==1.16.0
RUN pip install sseclient==0.0.27
RUN pip install torch==2.0.0

RUN pip install accelerate
RUN pip install sentencepiece==0.1.97
RUN pip install protobuf==3.20.2
RUN pip install transformers==4.29
RUN pip install tokenizers==0.13.3
#RUN pip install memray
USER root
CMD source /home/ray/.bashrc
