apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-cluster-1000g-volumeclaim-720
  namespace: kuberay
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi