apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-cluster-100g-volumeclaim-2x
  namespace: kuberay
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi